"""添加电商agent表

Revision ID: 46850258c6d7
Revises: d9320d8e8bf5
Create Date: 2026-09-30 11:20:20.489451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '46850258c6d7'
down_revision: Union[str, Sequence[str], None] = 'd9320d8e8bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_order', 'order_status',
               existing_type=mysql.TINYINT(),
               type_=sa.SmallInteger(),
               existing_comment='订单状态 0待付款 1已付款 2已发货 3已完成 4已取消 5售后中',
               existing_nullable=False)
    op.drop_index(op.f('idx_status'), table_name='t_order')
    op.drop_index(op.f('idx_user_id'), table_name='t_order')
    op.drop_index(op.f('uk_order_no'), table_name='t_order')
    op.create_index(op.f('ix_t_order_order_no'), 't_order', ['order_no'], unique=True)
    op.create_index(op.f('ix_t_order_order_status'), 't_order', ['order_status'], unique=False)
    op.create_index(op.f('ix_t_order_user_id'), 't_order', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_order_user_id'), table_name='t_order')
    op.drop_index(op.f('ix_t_order_order_status'), table_name='t_order')
    op.drop_index(op.f('ix_t_order_order_no'), table_name='t_order')
    op.create_index(op.f('uk_order_no'), 't_order', ['order_no'], unique=True)
    op.create_index(op.f('idx_user_id'), 't_order', ['user_id'], unique=False)
    op.create_index(op.f('idx_status'), 't_order', ['order_status'], unique=False)
    op.alter_column('t_order', 'order_status',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(),
               existing_comment='订单状态 0待付款 1已付款 2已发货 3已完成 4已取消 5售后中',
               existing_nullable=False)
    # ### end Alembic commands ###
