"""添加两张周考表 hero和country

Revision ID: d3448ec24ccd
Revises: 17f51e86d986
Create Date: 2026-09-18 14:24:41.307721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3448ec24ccd'
down_revision: Union[str, Sequence[str], None] = '17f51e86d986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False, comment='国家编号'),
    sa.Column('name', sa.String(length=30), nullable=False, comment='国家名称'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hero',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='英雄编号，正整数，全局唯一'),
    sa.Column('name', sa.String(length=30), nullable=False, comment='英雄名称，建议不超过30个字符'),
    sa.Column('power', sa.Integer(), nullable=False, comment='武力值，范围0-100'),
    sa.Column('countryId', sa.Integer(), nullable=False, comment='所属国家编号'),
    sa.ForeignKeyConstraint(['countryId'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero')
    op.drop_table('country')
    # ### end Alembic commands ###
