"""添加几张只能问答表v2

Revision ID: d9320d8e8bf5
Revises: d3448ec24ccd
Create Date: 2026-09-28 19:12:13.338268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9320d8e8bf5'
down_revision: Union[str, Sequence[str], None] = 'd3448ec24ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogue_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='会话UUID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('first_message', sa.Text(), nullable=False, comment='会话首消息'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogue_sessions_id'), 'dialogue_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_dialogue_sessions_user_id'), 'dialogue_sessions', ['user_id'], unique=False)
    op.create_table('dialogue_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='消息UUID'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色 user/ai'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['session_id'], ['dialogue_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogue_items_id'), 'dialogue_items', ['id'], unique=False)
    op.create_index(op.f('ix_dialogue_items_session_id'), 'dialogue_items', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dialogue_items_session_id'), table_name='dialogue_items')
    op.drop_index(op.f('ix_dialogue_items_id'), table_name='dialogue_items')
    op.drop_table('dialogue_items')
    op.drop_index(op.f('ix_dialogue_sessions_user_id'), table_name='dialogue_sessions')
    op.drop_index(op.f('ix_dialogue_sessions_id'), table_name='dialogue_sessions')
    op.drop_table('dialogue_sessions')
    # ### end Alembic commands ###
